version: "3"
services: 
    nginx:
        build: 
            context: ./nginx
            dockerfile: Dockerfile
        ports: 
            - 80:80
        restart: always
    server:
        build:
            context: ./server
            dockerfile: Dockerfile
        ports: 
            - 5000:80
    client:
        build: 
            context: ./client
            dockerfile: Dockerfile
        ports: 
            - 4200:80